/**
 * A trimmed sample of the generated `datalayer-events.ts`, matching its real syntax
 * (one `type X = …;` per line, one `"event": …;` per line in the map). Covers:
 * - `purchase`  — eventTarget GA4, references a named type (`EcommercePurchase`).
 * - `select_item` — a fat (11-member) string union to prove collapsing.
 * - `all_filters_closed` — minimal, eventTarget Amplitude.
 * - `dl_head` — no eventTarget (→ null).
 * Decls: `CommercialType` (2), `PageType` (8 — boundary, NOT collapsed),
 * `KameleoonGoalName` (10 — collapsed by getType), `EcommercePurchase` (object ref).
 */
export const DATALAYER_FIXTURE = `// AUTO-GENERATED by \`gulp generate-event-catalogs\`. Do not edit by hand.

/* eslint-disable */

type CommercialType = "dayuse" | "dayaccess";

type PageType = "home" | "search_page" | "hotel_page" | "confirmation_page" | "tunnel" | "partner_page" | "gift-card" | "other";

type KameleoonGoalName = "purchase" | "search" | "login" | "sign_up" | "view_item" | "share" | "refund" | "change_date" | "add_to_wishlist" | "select_item";

type EcommercePurchase = { currency: CommercialType; value: number; transaction_id: string };

export type DataLayerEvents = {
  "purchase": { event: "purchase"; ecommerce: EcommercePurchase; eventTarget: "GA4"; eventOrigin?: string & Record<string, never> | "Kameleoon" | "GTM" };
  "select_item": { event: "select_item"; eventTarget: "GA4"; item_list_name: "home::a" | "home::b" | "home::c" | "search::d" | "search::e" | "search::f" | "hotel::g" | "hotel::h" | "tunnel::i" | "tunnel::j" | "other::k" };
  "all_filters_closed": { event: "all_filters_closed"; eventTarget: "Amplitude" };
  "dl_head": { event: "dl_head"; site_currency: string };
};

export type DataLayerEventName = keyof DataLayerEvents;
`;
